// This file is automatically generated by vite. 
// It's purpose is to mount the React component tree 
// into the static HTML mount node (#root) in index.html.

import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.jsx'

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
